INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(1, 'Nhiếp ảnh, dựng phim', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(2, 'Hôn nhân & Gia đình', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(3, 'Phong cách sống', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(4, 'Sức khỏe - Giới tính', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(5, 'Công nghệ thông tin', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(6, 'Sale - Bán hàng', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(7, 'Phát triển cá nhân', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(8, 'Kinh doanh - Khởi nghiệp', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(9, 'Thiết kế', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(10, 'Tin học văn phòng', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(11, 'Marketing', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(12, 'Ngoại Ngữ', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(13, 'Đề Thi', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(14, 'Thư Viện Pháp Luật', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(15, 'Sách khoa học', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(16, 'Sách ngoại ngữ', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(17, 'Sách kinh doanh', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(18, 'Phát triển cá nhân', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(19, 'Sách văn học', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(20, 'Sách kinh tế', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(21, 'Ẩm thực - Nấu ăn', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(22, 'Tiểu thuyết', 1);
INSERT INTO catalog(catalog_id, name_catalog, admin_id) VALUES(23, 'Nông - Lâm - Ngư', 1);